version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/hugo
    steps:
      - checkout
      - run:
          name: clone also submodules (themes)
          command: git submodule update --init
      - run:
          name: Build html in ./public/
          command: hugo -v
      - setup_remote_docker
      - run:
          name: Docker build from html
          command: sudo docker build -t $hub_docker_user/repo1 .
      - run:
          name: Docker login
          command: sudo docker login -u $hub_docker_user -p $hub_docker_pw
      - run:
          name: Docker push
          command: sudo docker push $hub_docker_user/repo1

workflows:
  version: 2
  workflow_1:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
